-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.student
(
    email character varying(50) NOT NULL,
    password character varying(100) NOT NULL,
    s_id serial NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    current_level integer DEFAULT 0,
    CONSTRAINT user_pkey PRIMARY KEY (s_id)
);

CREATE TABLE IF NOT EXISTS public.lab
(
    id serial NOT NULL,
    modules integer[] NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student_lab
(
    student_s_id serial NOT NULL,
    lab_id serial NOT NULL,
    passed boolean NOT NULL,
    PRIMARY KEY (student_s_id, lab_id)
);

CREATE TABLE IF NOT EXISTS public.module
(
    id serial NOT NULL,
    assignments integer[],
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student_module
(
    student_s_id serial NOT NULL,
    module_id serial NOT NULL,
    passed boolean,
    PRIMARY KEY (student_s_id, module_id)
);

CREATE TABLE IF NOT EXISTS public.assignment
(
    id serial NOT NULL,
    assignment_text text NOT NULL,
    assignment_name text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student_assignment
(
    student_s_id serial NOT NULL,
    assignment_id serial NOT NULL,
    passed boolean NOT NULL,
    PRIMARY KEY (student_s_id, assignment_id)
);

ALTER TABLE IF EXISTS public.student_lab
    ADD FOREIGN KEY (student_s_id)
    REFERENCES public.student (s_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.student_lab
    ADD FOREIGN KEY (lab_id)
    REFERENCES public.lab (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.student_module
    ADD FOREIGN KEY (student_s_id)
    REFERENCES public.student (s_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.student_module
    ADD FOREIGN KEY (module_id)
    REFERENCES public.module (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.student_assignment
    ADD FOREIGN KEY (student_s_id)
    REFERENCES public.student (s_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.student_assignment
    ADD FOREIGN KEY (assignment_id)
    REFERENCES public.assignment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;