export const lab1Levels = [
  "1 \nPrinting",
  "2 \nVariables",
  "3 \nStrings",
  "4 \nScanner",
  "5 \nOperations",
  "6 \nClasses",
  "7 \nMethods",
  "8 \nFor-loop",
  "9 \nNested For-loop",
  "10 \nArrays",
  "11 \nMatrix",
  "12 \nIf-statement",
  "13 \nElse",
  "14 \nBoss 1",
  "1",
];
