export const lab1Levels = [
  "1 \nSystem.out",
  "2 \nVariables",
  "3 \nStrings",
  "4 \nScanner",
  "5 \nOperation",
  "6 \nClass",
  "7 \nMethod",
  "8 \nFor-loop",
  "9 \nFor-loop 2",
  "10 \nArray",
  "11 \nMatrix",
  "12 \nIf",
  "13 \nElse",
  "14 \nFinal Boss",
  "1",
];
