export const lab1Levels = [
  "1 \nClass",
  "2 \nMethod",
  "3 \nSystem.out",
  "4 \nString",
  "5 \nVariables",
  "6 \nOperation",
  "7 \nIf-loop",
  "8 \nElse",
  "9 \nFor-loop",
  "10 \nFor-loop 2",
  "11 \nArray",
  "12 \nMatrix",
  "13 \nScanner",
  "14 \nFinal Boss",
  "1",
];
