export const lab2Levels = [
  "1 \nInheritance",
  "2 \nPolymorphism",
  "3 \nAbstraction",
  "4 \nEncapsulation",
  "5 \nException Handling",
  "6 \nInterfaces",
  "7 \nGenerics",
  "8 \nLambda Expressions",
  "9 \nStreams",
  "10 \nSerialization",
  "11 \nMultithreading",
  "12 \nSynchronization",
  "13 \nConcurrency Utilities",
  "14 \nFinal Boss",
  "2",
];
