export const lab2Levels = [
  "15 \nBuffered Reader",
  "16 \nIOException",
  "17 \nFor-Each",
  "18 \nBoolean",
  "19 \nLogical Operators",
  "20 \nWhile-Loop",
  "21 \nString Array",
  "22 \nString Comparison",
  "23 \nLinked List",
  "24 \nArray Index Insertion",
  "25 \nDelete",
  "26 \nSelection Sort 1",
  "27 \nSelection Sort 2",
  "28 \nFinal Boss",
  "2",
];
