export const lab3Levels = [
  "29 \nObjects",
  "30 \nString Concatenation",
  "31 \nString Builder",
  "32 \nQueue",
  "33 \nBreak Statement",
  "34 \nPass by Reference",
  "35 \nCreating Linked List",
  "36 \nTraverse Linked LIst",
  "37 \nLinked List to Array",
  "38 \nNull",
  "39 \nDelete Linked List",
  "40 \nJava Library",
  "41 \nSwitch",
  "3",
];
